//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NküOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneOtoEntities : DbContext
    {
        public KutuphaneOtoEntities()
            : base("name=KutuphaneOtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kayit> kayit { get; set; }
        public virtual DbSet<kitapAra> kitapAra { get; set; }
        public virtual DbSet<kitapListele> kitapListele { get; set; }
        public virtual DbSet<Listeleme> Listeleme { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<new_kayit> new_kayit { get; set; }
    }
}
