//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NküOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayit
    {
        public int kayit_no { get; set; }
        public string tc { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tel { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public string adres { get; set; }
        public string foto { get; set; }
    }
}
