//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NküOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitapAra
    {
        public int barkod_no { get; set; }
        public string kitap_adi { get; set; }
        public string kitap_yazari { get; set; }
        public string yayin_evi { get; set; }
        public string kitap_turu { get; set; }
    }
}
